dist: xenial

language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
#  - hhvm

services:
  - postgresql

before_install:
  - php -r "echo phpinfo();"

  # From https://docs.travis-ci.com/user/languages/php
  # Currently Travis CI does not support mod_php for apache, but you can
  # configure php-fpm for your integration tests.

  # Update the package list.
  - sudo apt-get update
  # Reinstall PostgreSQL - see https://github.com/travis-ci/travis-ci/issues/7048#issuecomment-267731971
  - sudo apt-get autoremove postgis*
  - sudo apt-get autoremove postgresql*
  - sudo apt-get install postgresql-9.3-postgis-2.1
  # Install Apache.
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # Enable php-fpm.
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # Configure apache virtual hosts.
  - sudo cp -f .travis/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

install:
  # Grant execute on scripts
  - chmod +x .travis/postgres_setup.sh

before_script:
  - psql -c 'create database indicia;' -U postgres -d postgres
  # Add extension for PostGIS
  - psql -U postgres -d indicia -c "create extension postgis"
  - psql -U postgres -d indicia -c "create extension postgis_topology"
  # Set up database.
  - .travis/postgres_setup.sh
  # Enable the phpunit module in config.php (meaning initialise() is not tested)
  - cp application/config/config.php.travis application/config/config.php
  # Provide a config file for the rest_api module
  - cp modules/rest_api/config/rest.php.travis  modules/rest_api/config/rest.php
  # Downgrade to PHPUnit 5.7
  - wget https://phar.phpunit.de/phpunit-5.7.phar
  - chmod +x phpunit-5.7.phar
  - sudo mv phpunit-5.7.phar /usr/local/bin/phpunit

script:
  - /usr/local/bin/phpunit --configuration phpunit-config-test.xml
  - /usr/local/bin/phpunit --configuration phpunit-setup-check-test.xml
  - /usr/local/bin/phpunit --configuration phpunit-home-test.xml
  # Repeat to upgrade modules
  - /usr/local/bin/phpunit --configuration phpunit-home-test.xml
  - /usr/local/bin/phpunit --configuration phpunit-tests.xml

after_script:
  - cat application/logs/*
